apiVersion: v1
kind: ConfigMap
metadata:
  name: banco-digital-config
  namespace: banco-digital
data:
  DB_URL: jdbc:postgresql://postgres:5432/banco2026
  DB_USER: postgres
  DDL_AUTO: update
  PORT: "8080"
  SHOW_SQL: "false"
  HTTPS_SEGURO: "false"
  CORS_ORIGENES: http://localhost:3000,http://localhost:5173,http://localhost:8080
