apiVersion: v1
kind: Secret
metadata:
  name: banco-digital-secret
  namespace: banco-digital
type: Opaque
stringData:
  DB_PASS: postgres
  JWT_SECRET: BancoDigital2026ClaveSecretaSuperSeguraParaFirmarTokensJWTHS256
  POSTGRES_PASSWORD: postgres
