apiVersion: apps/v1
kind: Deployment
metadata:
  name: banco-digital-backend
  namespace: banco-digital
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banco-digital-backend
  template:
    metadata:
      labels:
        app: banco-digital-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: backend
          image: banco-digital-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: banco-digital-config
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: banco-digital-secret
                  key: DB_PASS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: banco-digital-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: banco-digital-backend
  namespace: banco-digital
  labels:
    app: banco-digital-backend
spec:
  selector:
    app: banco-digital-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
